---
kind: pipeline
type: docker
name: test
steps:
  - name: create-tags
    image: alpine
    commands:
      - echo "Deploying version $DRONE_SEMVER"
      - echo -n "$DRONE_SEMVER, latest" > .tags

  - name: docker-build
    image: plugins/docker
    settings:
      dry_run: true
      auto_tag: true
      repo: 'ghcr.io/ringsq/drone-k8s'
      registry: ghcr.io
      username:
        from_secret: github_username
      password:
        from_secret: github_token

trigger:
  event:
    - push

---
kind: pipeline
type: docker
name: docker-build
steps:
  - name: create-tags
    image: alpine
    commands:
      - echo "Deploying version $DRONE_SEMVER"
      - echo -n "$DRONE_SEMVER, latest" > .tags

  - name: build-push-image
    image: plugins/docker
    settings:
      auto_tag: false
      repo: 'ghcr.io/ringsq/drone-k8s'
      registry: ghcr.io
      username:
        from_secret: github_username
      password:
        from_secret: github_token

trigger:
  event:
    - tag
    - push
